package com.abassy.tables;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductoCompuesto generated by hbm2java
 */
@Entity
@Table(name = "producto_compuesto", catalog = "abassy_db")
public class ProductoCompuesto implements java.io.Serializable {

	private Integer id;
	private Producto productoByIdProducto;
	private Producto productoByIdCompuesto;

	public ProductoCompuesto() {
	}

	public ProductoCompuesto(Producto productoByIdProducto, Producto productoByIdCompuesto) {
		this.productoByIdProducto = productoByIdProducto;
		this.productoByIdCompuesto = productoByIdCompuesto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto")
	public Producto getProductoByIdProducto() {
		return this.productoByIdProducto;
	}

	public void setProductoByIdProducto(Producto productoByIdProducto) {
		this.productoByIdProducto = productoByIdProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_compuesto")
	public Producto getProductoByIdCompuesto() {
		return this.productoByIdCompuesto;
	}

	public void setProductoByIdCompuesto(Producto productoByIdCompuesto) {
		this.productoByIdCompuesto = productoByIdCompuesto;
	}

}
