package com.abassy.tables;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "abassy_db")
public class Producto implements java.io.Serializable {

	private Integer id;
	private FamiliaProducto familiaProducto;
	private String nombre;
	private Integer precio;
	private Integer tipo;
	private byte[] imagen;
	private Set<ProductoCompuesto> productoCompuestosForIdProducto = new HashSet<ProductoCompuesto>(0);
	private Set<LineaPedido> lineaPedidos = new HashSet<LineaPedido>(0);
	private Set<ProductoCompuesto> productoCompuestosForIdCompuesto = new HashSet<ProductoCompuesto>(0);

	public Producto() {
	}

	public Producto(FamiliaProducto familiaProducto, String nombre, Integer precio, Integer tipo, byte[] imagen,
			Set<ProductoCompuesto> productoCompuestosForIdProducto, Set<LineaPedido> lineaPedidos,
			Set<ProductoCompuesto> productoCompuestosForIdCompuesto) {
		this.familiaProducto = familiaProducto;
		this.nombre = nombre;
		this.precio = precio;
		this.tipo = tipo;
		this.imagen = imagen;
		this.productoCompuestosForIdProducto = productoCompuestosForIdProducto;
		this.lineaPedidos = lineaPedidos;
		this.productoCompuestosForIdCompuesto = productoCompuestosForIdCompuesto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_familia")
	public FamiliaProducto getFamiliaProducto() {
		return this.familiaProducto;
	}

	public void setFamiliaProducto(FamiliaProducto familiaProducto) {
		this.familiaProducto = familiaProducto;
	}

	@Column(name = "nombre", length = 65535)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio")
	public Integer getPrecio() {
		return this.precio;
	}

	public void setPrecio(Integer precio) {
		this.precio = precio;
	}

	@Column(name = "tipo")
	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	@Column(name = "imagen")
	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productoByIdProducto")
	public Set<ProductoCompuesto> getProductoCompuestosForIdProducto() {
		return this.productoCompuestosForIdProducto;
	}

	public void setProductoCompuestosForIdProducto(Set<ProductoCompuesto> productoCompuestosForIdProducto) {
		this.productoCompuestosForIdProducto = productoCompuestosForIdProducto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<LineaPedido> getLineaPedidos() {
		return this.lineaPedidos;
	}

	public void setLineaPedidos(Set<LineaPedido> lineaPedidos) {
		this.lineaPedidos = lineaPedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productoByIdCompuesto")
	public Set<ProductoCompuesto> getProductoCompuestosForIdCompuesto() {
		return this.productoCompuestosForIdCompuesto;
	}

	public void setProductoCompuestosForIdCompuesto(Set<ProductoCompuesto> productoCompuestosForIdCompuesto) {
		this.productoCompuestosForIdCompuesto = productoCompuestosForIdCompuesto;
	}

}
